import { View, Text, TextInput, TouchableOpacity, StyleSheet, Alert, ActivityIndicator } from 'react-native';
import { useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { authService } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function VerifyOtpScreen() {
    const router = useRouter();
    const { temp_token } = useLocalSearchParams();
    const { signIn } = useAuth();
    const [otp, setOtp] = useState('');
    const [loading, setLoading] = useState(false);

    const handleVerify = async () => {
        if (!otp || otp.length !== 6) {
            Alert.alert('Error', 'Please enter a valid 6-digit code');
            return;
        }

        if (typeof temp_token !== 'string') {
            Alert.alert('Error', 'Invalid session');
            router.replace('/login');
            return;
        }

        setLoading(true);
        try {
            const response = await authService.verifyOtp(temp_token, otp);
            await signIn(response.token, response.user);
        } catch (error: any) {
             Alert.alert('Verification Failed', error.response?.data?.error || 'Invalid code');
        } finally {
            setLoading(false);
        }
    };

    return (
        <SafeAreaView style={styles.container}>
            <View style={styles.header}>
                <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
                    <Text style={styles.backButtonText}>Cancel</Text>
                </TouchableOpacity>
            </View>

            <View style={styles.content}>
                <Text style={styles.title}>Two-Factor Authentication</Text>
                <Text style={styles.subtitle}>
                    Enter the code generated by your authenticator app.
                </Text>

                <TextInput
                    style={styles.input}
                    placeholder="000000"
                    placeholderTextColor="#333"
                    value={otp}
                    onChangeText={setOtp}
                    keyboardType="number-pad"
                    maxLength={6}
                    autoFocus
                />

                <TouchableOpacity 
                    style={[styles.button, otp.length !== 6 && styles.buttonDisabled]} 
                    onPress={handleVerify}
                    disabled={loading || otp.length !== 6}
                >
                    {loading ? (
                        <ActivityIndicator color="#000" />
                    ) : (
                        <Text style={styles.buttonText}>Verify</Text>
                    )}
                </TouchableOpacity>
            </View>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000000',
        paddingHorizontal: 20,
    },
    header: {
        paddingVertical: 10,
    },
    backButton: {
        padding: 10,
    },
    backButtonText: {
        color: '#ffffff',
        fontSize: 16,
    },
    content: {
        flex: 1,
        paddingTop: 40,
        alignItems: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#ffffff',
    },
    subtitle: {
        fontSize: 16,
        color: '#71767b',
        textAlign: 'center',
        marginBottom: 40,
    },
    input: {
        borderBottomWidth: 2,
        borderBottomColor: '#1d9bf0',
        paddingVertical: 10,
        paddingHorizontal: 20,
        fontSize: 32,
        fontWeight: 'bold',
        marginBottom: 40,
        letterSpacing: 5,
        textAlign: 'center',
        width: '80%',
        color: '#ffffff',
    },
    button: {
        backgroundColor: '#ffffff',
        paddingVertical: 15,
        paddingHorizontal: 40,
        borderRadius: 4,
        alignItems: 'center',
        width: '100%',
    },
    buttonDisabled: {
        opacity: 0.5,
    },
    buttonText: {
        color: '#000000',
        fontSize: 16,
        fontWeight: 'bold',
    },
});